# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:mac)

platform :mac do
  desc "Description of what the lane does"
  lane :custom_lane do
   run_tests(scheme: "SwiftUtilTests")
    # add actions here: https://docs.fastlane.tools/actions
  end

  desc "Run tests"
  lane :testbuild do
    run_tests(scheme: "SwiftUtilTests")
  end

  desc "Push a new release on github"
  lane :put_github do
    increment_version_number(bump_type: "minor")
  end
  
end
