# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:mac)

platform :mac do
  lane :build do
    gym(scheme: "PassGen", destination: "platform=macOS")
#    build_mac_app(project: "PassGen.xcodeproj", scheme: "PassGen", destination: "platform=macOS")
  end

  desc "Push a new release on github"
  lane :release do
    increment_version_number_in_xcodeproj(bump_type: "patch", target: "PassGen")
    commit_version_bump
    add_git_tag(tag: "#{get_version_number}(#{get_build_number})")
    push_to_git_remote
  end

end
